# NWN Server Docker file - Step 1
FROM i386/debian:buster-slim

# ---------------------------------------------
LABEL Name=NWN-EE-Crawl-Base version=1.0

# ---------------------------------------------
WORKDIR /opt/nwserver
COPY ./nwserver /opt/nwserver

#CMD ["bin/linux-x86/nwserver-linux", "-interactive"]
